/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include <memory.h> /* for memset */
#include "l2tp_event_rpc.h"

/* Default timeout can be changed using clnt_control() */
static struct timeval TIMEOUT = { 25, 0 };

enum clnt_stat 
l2tp_session_ppp_updown_ind_1(uint16_t tunnel_id, uint16_t session_id, int unit, bool_t up, void *clnt_res,  CLIENT *clnt)
{
	l2tp_session_ppp_updown_ind_1_argument arg;
	arg.tunnel_id = tunnel_id;
	arg.session_id = session_id;
	arg.unit = unit;
	arg.up = up;
	return (clnt_call (clnt, L2TP_SESSION_PPP_UPDOWN_IND, (xdrproc_t) xdr_l2tp_session_ppp_updown_ind_1_argument, (caddr_t) &arg,
		(xdrproc_t) xdr_void, (caddr_t) clnt_res,
		TIMEOUT));
}

enum clnt_stat 
l2tp_session_ppp_status_ind_1(uint16_t tunnel_id, uint16_t session_id, int result, void *clnt_res,  CLIENT *clnt)
{
	l2tp_session_ppp_status_ind_1_argument arg;
	arg.tunnel_id = tunnel_id;
	arg.session_id = session_id;
	arg.result = result;
	return (clnt_call (clnt, L2TP_SESSION_PPP_STATUS_IND, (xdrproc_t) xdr_l2tp_session_ppp_status_ind_1_argument, (caddr_t) &arg,
		(xdrproc_t) xdr_void, (caddr_t) clnt_res,
		TIMEOUT));
}

enum clnt_stat 
l2tp_session_ppp_accm_ind_1(uint16_t tunnel_id, uint16_t session_id, uint32_t send_accm, uint32_t recv_accm, void *clnt_res,  CLIENT *clnt)
{
	l2tp_session_ppp_accm_ind_1_argument arg;
	arg.tunnel_id = tunnel_id;
	arg.session_id = session_id;
	arg.send_accm = send_accm;
	arg.recv_accm = recv_accm;
	return (clnt_call (clnt, L2TP_SESSION_PPP_ACCM_IND, (xdrproc_t) xdr_l2tp_session_ppp_accm_ind_1_argument, (caddr_t) &arg,
		(xdrproc_t) xdr_void, (caddr_t) clnt_res,
		TIMEOUT));
}
