#
# milli_httpd Makefile
#
# Copyright (C) 2001 Broadcom Corporation
#
# $Id: Makefile,v 1.2 2003/11/17 13:34:10 Cheni_Shen Exp $
#
TOP=/root/broadcom.WirelessHD/src/router
SRCBASE=/root/broadcom.WirelessHD/src
INSTALLDIR=/root/broadcom.WirelessHD/src/router/mipsel-uclibc/install

CFLAGS	+= -I. -Wall -Dlinux -DNO_PARALLEL -DWCLIENT -I$(TOP)/shared -I$(SRCBASE)/include #-DWL300g
#CFLAGS	+= -g -DDEBUG
#CFLAGS	+= -s -O2 
#LDFLAGS	+= -Wl,-elf2flt="" #-L$(TOP)/nvram
LDFLAGS += -L$(TOP)/nvram -L$(INSTALLDIR)/nvram/usr/lib -lnvram -L$(TOP)/shared -L$(INSTALLDIR)/shared/usr/lib -lshared
CC = mipsel-uclibc-gcc
STRIP = mipsel-uclibc-strip

vpath %.c $(TOP)/shared

all: infosvr

clean:
	rm -f *.o *~ infosvr

install: all
# Neo
#	install -d $(INSTALLDIR)/usr/sbin
#	install httpd $(INSTALLDIR)/usr/sbin
#	$(STRIP) $(INSTALLDIR)/usr/sbin/httpd

	install -d $(INSTALLDIR)/sbin
	#$(STRIP) infosvr
	install infosvr $(INSTALLDIR)/sbin

infosvr: ./infosvr.o ./wlutils.o ./common.o 
	$(CC) -o $@ $^ $(LDFLAGS) $(CFLAGS)

