/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "l2tp_event_rpc.h"

bool_t
xdr_l2tp_session_ppp_updown_ind_1_argument (XDR *xdrs, l2tp_session_ppp_updown_ind_1_argument *objp)
{
	 if (!xdr_uint16_t (xdrs, &objp->tunnel_id))
		 return FALSE;
	 if (!xdr_uint16_t (xdrs, &objp->session_id))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->unit))
		 return FALSE;
	 if (!xdr_bool (xdrs, &objp->up))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_l2tp_session_ppp_status_ind_1_argument (XDR *xdrs, l2tp_session_ppp_status_ind_1_argument *objp)
{
	 if (!xdr_uint16_t (xdrs, &objp->tunnel_id))
		 return FALSE;
	 if (!xdr_uint16_t (xdrs, &objp->session_id))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->result))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_l2tp_session_ppp_accm_ind_1_argument (XDR *xdrs, l2tp_session_ppp_accm_ind_1_argument *objp)
{
	 if (!xdr_uint16_t (xdrs, &objp->tunnel_id))
		 return FALSE;
	 if (!xdr_uint16_t (xdrs, &objp->session_id))
		 return FALSE;
	 if (!xdr_uint32_t (xdrs, &objp->send_accm))
		 return FALSE;
	 if (!xdr_uint32_t (xdrs, &objp->recv_accm))
		 return FALSE;
	return TRUE;
}
